#server:
#  port: 9192

spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/lakeSide_hotel_db
#    url: jdbc:mariadb://localhost:3306/lakeSide_hotel_maria
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB